// flow-typed signature: 9f061b0ff6c15293cedfbbe1c4f71eb4
// flow-typed version: <<STUB>>/env-test_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'env-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'env-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'env-test/index' {
  declare module.exports: $Exports<'env-test'>;
}
declare module 'env-test/index.js' {
  declare module.exports: $Exports<'env-test'>;
}
